services:
  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:?set in .env}
    command: >
      sh -lc 'redis-server --save 20 1 --loglevel warning --requirepass "$$REDIS_PASSWORD"'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
